### ISSUE TITLE
Why newHeader?

### ISSUE THREAD

**Issue by Annihil** [jet2jet/pe-library-js#7]
Hi,
First of all thanks for this great library.
I was wondering, why is `ntHeader` called `newHeader` everywhere, is this a typo or was it intended?
https://github.com/jet2jet/pe-library-js/blob/6448241f0db34d349ca3031160e0111c07160430/src/main/NtExecutable.ts#L186
https://github.com/jet2jet/pe-library-js/blob/6448241f0db34d349ca3031160e0111c07160430/src/main/format/ImageDosHeader.ts#L121
Let me know :)

**Comment by jet2jet** [comment]
This is an intended name, based on `e_lfanew` in `IMAGE_DOS_HEADER`. `new` means the new executable (PE executable is newer than DOS executable), but in PE format, 'new executable' always refers to NT header (`IMAGE_NT_HEADERS`).  
This Q&A may help you: https://stackoverflow.com/questions/47711282/what-does-e-lfanew-mean-in-the-dos-header-for-the-pe-format

**Comment by Annihil** [comment]
Ah fair enough, good to know, thanks! :)
